pool:
  name: $(pool_name)
  vmImage: 'ubuntu-latest'
steps:
  - task: UseDotNet@2
    displayName: .NET Core 3.1.x
    inputs:
      version: 3.1.x
      packageType: sdk
  - task: ShellScript@2
    displayName: test
    inputs:
      scriptPath: test.sh
trigger: [ master ]
workspace: { clean: all }